name: Unit Tests

on:
    pull_request:
        branches:
            - master

jobs:
    unit-test-84:
        name: Run PHPUnit on PHP 8.4 Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout the repository code
                uses: actions/checkout@v4
            -   name: Composer install
                uses: php-actions/composer@v6
                with:
                    php_version: 8.4
                    version: 2
                    dev: yes
            -   name: PHPUnit
                run: "./vendor/bin/phpunit"

    unit-test-85:
        name: Run PHPUnit on PHP 8.5 Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout the repository code
                uses: actions/checkout@v4
            -   name: Composer install
                uses: php-actions/composer@v6
                with:
                    php_version: 8.5
                    version: 2
                    dev: yes
            -   name: PHPUnit
                run: "./vendor/bin/phpunit"